RedisJSON/RedisJSON

- .travis.yml
- src/object.c
This bug does not allow (and will cause crash on) objects larger than 1M elements.
> Fixed error in realloc in objects

- src/json_object.c
- test/pytest/test.py
Fixes the issue in serialization that falsely uses the `%g` flag and causes double precision float points to lose precision.
> Prevent float point serialization losing precision, fixes #6

- src/json_path.c
- src/json_path.h
- src/rejson.c
- src/rejson.h
- test/test_object.c
Search path errors now report the type of error and the offset in
the path. This also fixes a subtle issue of keys starting with a
digit immediately after the root (i.e. '.1foo') not producing an
error.
Fixes #11
> Adds verbosity to search path errors

- src/json_type.c
Removes enclosing redundant double quotes.
This resolves #14, but still leaves two uncovered topics:
1. AOF tests are missing
2. Need to capture and report the currently-silent AOF loading errors
> Fixes serialization to AOF

- .travis.yml
- docs/commands.md
- src/json_object.c
- src/json_object.h
- src/rejson.c
- test/pytest/test.py
This allows the return of "raw" JSON string data. In reality this should
be the default (and we should never need to escape anything that doesn't
need escaping per the standard), but we don't want to break apps who are
using it to transport "binary" data.
> Add `NOESCAPE` option

- .travis.yml
To protect from breaking changes, until we complete the RP release, let's fix RAMP on version 1.2.3 in travis.
> Fix version number of RAMP packaging script

- docs/index.md
links to redis-py fork instead of rejson-py
> docs - fix rejson-py git link

- docs/index.md
go-rejson now supports multiple clients (redigo, go-redis). More client support coming soon.
> go-rejson now supports multiple clients

- docs/index.md
Looks like a URL to the NReJSON library made its way into the body of the quick start. 
Updated the client table with the license scheme of NReJSON.
> Removed random link to and update license scheme..

- docs/index.md
One of the code blocks in quickstart guide is broken.
https://oss.redislabs.com/redisjson/#quickstart
> Fix a code block in quickstart docs

- README.md
I've added another Node.js package that contains support for RedisJSON
> Adding redis-modules-sdk Node.js client to README

- .github/workflows/deploy-docs.yaml
Ensure old pages from the doc are removed.
> After some time, files may be removed from the documentation but they will still reside in the site directory. To remove those stale files, just run mkdocs with the --clean switch.
https://www.mkdocs.org/#building-the-site
> Most importantly, --delete permanently deletes files in the S3 bucket that are not present in the latest version of your repository/build
https://github.com/jakejarvis/s3-sync-action
> Delete old pages from the doc

- docs/index.md
As mentioned in https://github.com/RedisJSON/RedisJSON/issues/262 , I came upon some additional packages needed on Ubuntu 20.04. I have added a subsection under "Building and Loading" in docs/index.md.
> added Ubuntu 20.04 build instructions to docs

- src/c_api.rs
This reverts commit 57f10c24
Fix is done in better way by commit 036cb51 in redismodule-rs
"WIP open_with_redis_string does not take ownership of the RedisModuleString"
> Revert "WIP Do not take ownership of RedisModuleString passed to JSONAPI_openKey

- Cargo.toml
> Fixed redismodule-rs crate version #

- src/lib.rs
- src/redisjson.rs
- tests/pytest/test.py
> Fix json.arrappend performance

- src/lib.rs
- src/redisjson.rs
Add fake load of schema information from documents that were stored in earlier versions
> Backward RDB load of older versions with Search schema emedded 

- src/lib.rs
- tests/pytest/test.py
> JSON.INSERTARR backward compatability for 1.0

- tests/benchmarks/json_vs_hashes_hset_key_simple.yml
- tests/benchmarks/json_vs_hashes_json.set_key_simple.yml
The following PR introduces two extra benchmarks ( each should take ~=1min to run ) focusing on comparing HSET vs JSON.SET equivalent on  a very simple use case: `HSET key_hash field1 value1 field2 value2` vs `JSON.SET key_json . {"field1":"value1","field2":"value2"}`.
> [add] Included hset vs json comparison benchmark use-cases

- Makefile
Further notes on:
- https://users.rust-lang.org/t/opt-level-2-removes-debug-symbols-needed-in-perf-profiling/16835/8
- https://stackoverflow.com/questions/38803760/how-to-get-a-release-build-with-debugging-information-when-using-cargo
> Release build with profile build flags when PROFILE=1  ( keep symbols, use optimizations, and keep frame pointer )

- src/lib.rs
Fixes #389, moving from 137919 ops/sec to 148139 ops/sec. 
To check locally:
```
make build benchmark BENCHMARK=json_get_array_of_docs[1]sclr_pass_100_json.yml
```
Overall difference:
```
"test","rps","avg_latency_ms","min_latency_ms","p50_latency_ms","p95_latency_ms","p99_latency_ms","max_latency_ms"\n
"master -- JSON.GET pass-100 array_of_docs[1].sclr","137919.62","0.110","0.016","0.103","0.151","0.159","3.895"\n'
"branch --  JSON.GET pass-100 array_of_docs[1].sclr","148139.38","0.103","0.016","0.095","0.143","0.143","0.503"\n'
```
> [perf] Only use arg.to_uppercase() on json_get when argument size is feasible to be a keyword

- Cargo.lock
- Cargo.toml
To take advantage of [redismodule-rs PR 156](https://github.com/RedisLabsModules/redismodule-rs/pull/156)
> Bump version of deps: redismodule to 0.18.0 and strum_macros to 0.21.1

- src/commands.rs
- src/lib.rs
- src/redisjson.rs
This should reduce the useless clone of the path when there is no need for backward compatibility with RedisJSON 1.0.x
> avoid path clone when not needed

- src/commands.rs
- tests/pytest/test_multi.py
Fix #502
Fix #504 
In addition, handle/add tests for other default args: objkeys objlen resp get strappend arrpop
> Multipath: handle default arguments

- src/manager.rs
- src/redisjson.rs
- tests/pytest/test_multi.py
`JSON.DEL` with a path leading to a json `null` should be counted by the return value
> JSON.DEL count deleted null value

- docs/ram.md
The file paths mentioned contained `/test/` when it must be `/tests/`.
> Rectify file paths in `ram.md` doc

- docs/performance.md
The `test` folder seems to have been renamed as `tests`.
That broke the link to the `pass-100.json` file.
> Fix `pass-100.json` test file path in performance.md

- src/commands.rs
- src/ivalue_manager.rs
- src/lib.rs
- src/manager.rs
- tests/pytest/test.py
- tests/pytest/test_keyspace_notifications.py
- tests/pytest/test_multi.py
1) Enable `JSON.CLEAR` on numeric scalars (in addition to clearing containers (Array and Object(Map))
2) Avoid clearing already cleared values
> Enable JSON.CLEAR on numeric scalars

- src/commands.rs
- tests/pytest/test.py
This PR addresses https://github.com/RedisJSON/RedisJSON/issues/592, although I'd like some feedback from other contributors on how I fixed it as I'm not sure if this is intentional behavior.
This does not modify the mutations made to the document, but instead stops returning an out-of-range error when doing an NX set to an array element that is, in fact, in range.
> Return no updates when performing an NX set to an existing array element

- src/ivalue_manager.rs
- src/manager.rs
- tests/pytest/test.py
Incrementing beyond range of number is crashing redis
```
127.0.0.1:6379> JSON.SET key $ 1.6350000000001314e+308
OK
127.0.0.1:6379> JSON.NUMINCRBY key $ 1.6350000000001314e+308
```
The problem was that `update` method was taking the value being updated, e.g., then applying a closure on it, and then setting the value to the value returned from the closure, and 2 problems could have been caused:
1) The closure could have failed, e.g., on a numeric overflow - and was unwrapped
2) Value was not being restored upon error, leaving a null in place of the previous value
The fix is to handle errors properly, and to set the value by ref, so it is not lost on error.
No public API was broken.
More details:
About `replace`
```
///
/// Replaces a value at a given `path`, starting from `root`
///
/// …
```
> Avoid crash on overflow in numincrby or nummultby

- docs/commands.md
The option to use `JSON.SET` with an existing path, except for the last element, which is missing, was not documented.
Related to #618
> Document adding a new child with JSON.SET

- docs/indexing_JSON.md
Noticed there was not any explenation as to how to index JSON arrays, adding that here - similar to redisearch/redisearch#2523
> Indexed array explainer

- commands.json
- docs/commands.md
`JSON.CLEAR` now supports clearing scalars (numeric, string, bool)
> DOC update JSON.CLEAR to also clear scalars

- src/commands.rs
Completion of #644 for RedisJsonHdt where key might fail to open since not registered as HDT key
> MOD-2511: do not fail MGET on wrong/unregistered key type

- tests/pytest/requirements.txt
Using RLTest version 0.5.0 is breaking the build
```
redis.exceptions.RedisClusterException: No way to dispatch this command to Redis Cluster. Missing key.
You can execute the command by specifying target nodes.
Command: ('config', 'set', 'notify-keyspace-events', 'KEA')
```
> Pin RLTest to 0.4.2 and update readies

- docs/commands.md
> Update doc on return value of JSON.TOGGLE (already in 2.0)

- Cargo.lock
- Cargo.toml
- tests/pytest/test.py
Moving to use the latest commit in our jsonpath branch with the required fix https://github.com/RedisJSON/jsonpath/pull/22
Test already exists in jsonpath repo, and adding a similar test also to RedisJSON repo.
> Add test to MOD2099 + update dep to latest generic_json_path

- docs/index.md
Fixed the Python example to work with the current stable version of redis-py.
- `https://github.com/andymccurdy/redis-py` redirects to `https://github.com/redis/redis-py`
- `r.json().set` (also) accepts a dictionary type as `obj`, manual JSON serialization is not required [1]
- `r.json().get` returns a list, not a deserializable str instance. Renamed `reply` to `results` to make that clearer. The contained list items are already deserialized to dictionary types [2]
[1] https://github.com/redis/redis-py/blob/master/redis/commands/json/commands.py#L215
[2] https://github.com/redis/redis-py/blob/master/redis/commands/json/commands.py#L173
> Fixed Python example

- .circleci/config.yml
Temporarily disabled focal for ARM as it is not yet present in RediSearch.
> [2.0] Temporarily disabled focal for ARM

- commands.json
> JSON.DEBUG MEMORY: make `key` arg mandatory in doc

- .gitignore
- Cargo.lock
- Cargo.toml
- src/c_api.rs
- src/commands.rs
- src/include/rejson_api.h
- src/lib.rs
- src/nodevisitor.rs
Adding JSON API Version 2,
Currently with new APIs `pathIsStatic` and `pathHasDefinedOrder`
ReJSON is exporting both API Versions 1 and 2, so it could still be used by an older RediSearch module.
> Add RedisJSON_V2 API with getPathInfoFlags

- .circleci/config.yml
- tests/pytest/test.py
Added check to JSON COPY test to prevent running on older redis-server versions where it is not relevant.
> Remove inapplicable test on unsupported version

- docs/commands/json.set.md
Minor change for consistency -- json.get -> JSON.GET
> Fix capitalization of JSON.SET multi path example

- src/c_api.rs
- src/lib.rs
Fix use declarations for other crates using the macro `redis_json_module_create`
> Fix use for crates using `redis_json_module_create`

- src/lib.rs
Improve #780 
Use `$crate` in a `use` declaration in the macro definition.
> Better fix for use for crates using `redis_json_module_create`

- docs/docs/path.md
@gkorland, this is a fix for the links to the command reference pages included in the JSONPath doc. During my last commit, I didn't realize the commands would link automatically when enclosed within backticks.
> Path doc: fixed command links

- docs/docs/path.md
Fix #796 Clarified that key naming rules apply to legacy path syntax.
> Key naming rules are for legacy path syntax

- src/c_api.rs
- src/include/rejson_api.h
- src/lib.rs
Add an API to get JSON string representation from a JSON Iterator.
Required to serialize multiple values, such as values obtained from a JSONPath with wildcards, etc., for example, `$..field[*]`.
Used by https://github.com/RediSearch/RediSearch/pull/3060
MOD-4152
> Add C API `getJSONFromIter`

- src/c_api.rs
- src/include/rejson_api.h
- src/lib.rs
Add API to reset an iterator, so it could be re-iterated (avoid re-opening key or re-parsing the JSONPath)
Related https://github.com/RediSearch/RediSearch/pull/3060
> Add JSON C API `resetIter`

- src/jsonpath/grammer.pest
- tests/rust_tests/filter.rs
Fix #614 
Initial fix was done by #699 and this is a completion fix for compilation failure of a path such as
```
"$.friends[?(@.id >= 2 || @.id == 4 || @.id == 6)].name"
```
With an error such as
```
"\"$.friends[?(@.id >= 2 || @.id ==  ---->>>> 4 || @.id == 6)].name\", expected one of the following: from_current, from_root." }'
```
> MOD-4431: Allow repetition of filter relation instead of optional

- Cargo.lock
- Cargo.toml
- docs/docs/path.md
- src/jsonpath/json_path.rs
- tests/pytest/test.py
- tests/rust_tests/op.rs
MOD-4432
* Add to JSONPath filter the regexp match operator
* Improve coverage
* Minor cosmetics
* Allow match using regex pattern from a field and add end-to-end test
* Test with numeric combined in filter
* Add more tests and documentation
(cherry picked from commit c4483f915e885a75b20edd19b3c2efe8d37e5a8f)
> [2.4] cherry-pick to 2.4 jsonpath filter regex

- src/c_api.rs
- src/include/rejson_api.h
RedisJSON 2.2 was released with JSON API VER 2.
Since apis were added since, version number must be incremented.
Related https://github.com/RediSearch/RediSearch/pull/3232
> MOD-4480: Bump latest JSON API version to RedisJSON_V3

- README.md
Redisson supports JSON commands since 3.17.4 version.
JSONBucket object reference
https://github.com/redisson/redisson/wiki/6.-distributed-objects/#615-json-object-holder
JSON commands mapping reference
https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping
> Redisson client added to the list

- docs/commands/json.arrindex.md
- src/commands.rs
- tests/pytest/test.py
- tests/pytest/test_multi.py
fix #886 
```
127.0.0.1:6379> json.set a $ '{"a":[[1, 2], [2,3]], "b":[[2,4], [1,2]]}'
OK
127.0.0.1:6379> JSON.ARRINDEX a $.* '[1,2]'
1) (integer) 0
2) (integer) 1
127.0.0.1:6379> json.set a $ '{"a":[{"b":1}, {"c":2}], "b":[{"b":1}, {"c":2}]}'
OK
127.0.0.1:6379> JSON.ARRINDEX a $.* '{"c":2}'
1) (integer) 1
2) (integer) 1
```
> Allow JSON.ARRINDEX with none scalar values

- .github/wordlist.txt
- Cargo.lock
- Cargo.toml
- src/jsonpath/json_path.rs
- src/jsonpath/mod.rs
- tests/pytest/test.py
- tests/rust_tests/common.rs
* enable tracing jsonpath tests
* add flow test
* Evaluate all filter operands
* Add tests with precedence and nesting
* update spellcheck dictionary
* remove redis-module from dev-dependencies
(cherry picked from commit 6b30093e01ff9a52d89820dbb42e9e4552964f27)
> [2.4] MOD-4602: handle jsonpath filter with 3 or more operands

- redis_json/src/commands.rs
- redis_json/src/ivalue_manager.rs
- redis_json/src/manager.rs
The PR changes `arr_pop` to accept value serialisation callback. This makes the API simpler for `SelectValue` implementations that does not return the popped value. The serialisation callback gets a reference to the popped value `RedisResult` that can directly send to the user.
The PR also changes IValue manager to follow the new API.
MOD-5389
Continuation of #1046
> Modify arr_pop to accept value serialization callback

- redis_json/src/c_api.rs
- redis_json/src/commands.rs
- redis_json/src/formatter.rs
- redis_json/src/ivalue_manager.rs
- redis_json/src/key_value.rs
- redis_json/src/redisjson.rs
- tests/pytest/test_resp3.py
* `JSON.GET`
Rename `JSON` to `EXPAND1`
Default is `STRING`
* `JSON.ARRPOP`
Rename `STRING` to `STRINGS`
Rename `JSON` to `EXPAND1`
Default is `STRINGS`
Followup PR:
Support FORMAT `STRINGS` in `JSON.GET` to return an array of arrays of STRING
(as with `JSON.ARRPOP`)
> MOD-5606: Rename FORMAT args and change defaults

- Cargo.lock
- Cargo.toml
Cherry-pick #1072
(cherry picked from commit 99f7cef037cc3f719fe755c9732359dd98260ee2)
> [2.6] MOD-5705: Cherry-pick Restrict the serde_derive version updates (#1072)

- .circleci/config.yml
- tests/pytest/test.py
- tests/pytest/test_multi.py
- tests/pytest/test_resp3.py
**Description:**
Make sure all keys used in `JSON.MGET` tests are on the same shard.
> MOD-5943: Fix mget test failures with redis unstable 

- tests/pytest/test.py
- tests/pytest/test_multi.py
- tests/pytest/test_resp3.py
* mget tests: put all keys on the same shard
* Fix test.py:testMgetCommand
Cherry-pick #1110 
(cherry picked from commit 1de881ca90a8c33e6cf3c2d7bfba03ca24357784)
> [2.6] MOD-5943: Fix mget test failures with redis unstable

- Makefile
MOD-5973
Align with https://github.com/RedisLabsModules/readies/commit/aaa8b902b5dee80c5f488c15ba0eb0b3730786f5
> MOD-5973: default macOS/x64 back to stable

- Cargo.lock
- Cargo.toml
Add `proc-macro2` to cargo.toml with its latest version (1.0.66), as the previous auto-generated one (1.0.56) fails to build with sanitizer in RediSearch upon testing 2.6 against RedisJSON 2.4 (see https://github.com/rust-lang/rust/issues/113152)
> Fix proc macro2 build

- .circleci/config.yml
- sbin/upload-artifacts
This temporary fix will allow testing RediSearch against the proper RedisJSON artifacts. 
RediSearch OSS expects to find RedisJSON up to date module in `rejson-oss/snapshots/` path, where the name of the zip file is `rejson-oss.<os>-<platform>-<arch>.<branch_name>.zip`. 
This had been broken due to incompatibility between the file name that was packed (arm arch name was changed to `aarch64` and macos for x86 was changed to catalina) and the expected filename to upload - hence the fix in the `upload-artifacts` script.
In addition, the snapshots were uploaded into a different path ("staging") at some point - and hence the change in`upload-artifacts` step in cirecle-ci.
Also, I added macOS builds to run on the integration branch as well, so we will have the updated artifacts for the master …
> upload snapshots for integration branches as well [MOD-6102]

- .circleci/config.yml
- sbin/pack.sh
- sbin/upload-artifacts
In Akita version and in redistack 6.2.x we are still using `arm64v8` as the arch name - reverting
> Revert arm name for Akita

- redis_json/src/c_api.rs
- redis_json/src/commands.rs
- tests/pytest/test_resp3.py
**Describe the changes in the pull request**
1. In RE 7.2, we introduced a breaking change on RESP3 to JSON commands by changing the default value for `path` argument from `.` to `$`.
2. This led to poor DevEx for popular use cases.
3.  This PR reverts that change.
**Which issues this PR fixes**
1. MOD-6156
**Main objects this PR modified**
1. `commands.rs`
**Mark if applicable**
> MOD-6156: Revert change to update default path to '$'

- Makefile
- sbin/system-setup.py
Tests fail using 0.7.7
```
Error in sys.excepthook:
Traceback (most recent call last):
File "/root/.local/lib/python3.9/site-packages/progressbar/utils.py", line 350, in flush
self.stdout._flush()
File "/root/.local/lib/python3.9/site-packages/progressbar/utils.py", line 224, in _flush
self.target.write(value)
OSError: [Errno 9] Bad file descriptor
```
> MOD-6283: Rollback to use RLTest=0.7.5

- docs/commands/json.merge.md
The example execution will return an error:
```
redis> JSON.SET doc $ '{"f1": {"a":1}, "f2":{"a":2}}'
OK
redis> JSON.GET doc
"{\"f1\":{\"a\":1},\"f2\":{\"a\":2}}"
redis> JSON.MERGE doc $ '{"f1": 'null', "f2":{"a":3, "b":4}, "f3":'[2,4,6]'}'
Invalid argument(s)
redis> JSON.MERGE doc $ '{"f1": null, "f2":{"a":3, "b":4}, "f3":[2,4,6]}' 
OK
redis> JSON.GET doc"{\"f2\":{\"a\":3,\"b\":4},\"f3\":[2,4,6]}"
```
> Fix the error example that cannot be executed in json.merge

- docs/commands/json.type.md
The command forgot to record the corresponding response.
> Update JSON.TYPE dummy response is empty array

- docs/commands/json.mset.md
In fact, executing the example directly will return this error:
```
redis> flushall
OK
redis> JSON.MSET doc1 $ '{"a":2}' doc2 $.f.a '3' doc3 $ '{"f1": {"a":1}, "f2":{"a":2}}'
(error) ERR new objects must be created at the root
```
Add some JSON.SET in front of the example to avoid error and fix
the incorrect responses.
> Fix execution examples in JSON MSET doc

- .circleci/config.yml
- tests/pytest/test.py
- tests/pytest/test_multi.py
If the test runs on redis unstable cluster, skipt MGET tests
> [2.4] Skip MGET test on redis unstable cluster

- .gitignore
- tests/pytest/test.py
- tests/pytest/test_multi.py
Backport of #1110 to 2.4
Only the non RESP-3 parts are relevant.
> [2.4] Fix mget test failures with redis unstable [MOD-6285, MOD-5943]

- Cargo.lock
update ahash to fix build
```
error[E0635]: unknown feature `stdsimd`
--> /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
|
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
|  
```
refs:
https://users.rust-lang.org/t/error-e0635-unknown-feature-stdsimd/106445
https://github.com/tkaitchuck/aHash/issues/200
> Update ahash version

- Cargo.lock
- redis_json/src/ivalue_manager.rs
- tests/pytest/test.py
- tests/pytest/test_multi.py
There were reports that Redis json modules couldn't handle the unicode characters in strings. This commit adds two tests to make sure those are handled fine for RedisJSON.
P.S. I apologise for the "irrelevant" changes, my IDE removes all the free-standing spaces on lines, as well as the trailing spaces. This actually helps to reduce the 'char noise' and reduces the size of the files :-)
> Add test to verify the unicode characters parse fine.

- tests/pytest/tests.sh
If the status file does not exist and we are creating it, don't fail with an error if the file doesn't exist; it obviously won't exist until we create it. This change creates the file in case it didn't exist, resulting in the proper continuation of the script and a proper exit code.
This change is also required for the repeatability of the CI steps locally. Namely in https://github.com/RedisJSON/RedisJsonHdt/pull/226
> Fix the tests.sh script.

- README.md
These two links were giving a 404, likely because of the rebrand/doc shuffle.
> Fix old links in the README

- .circleci/config.yml
The opereto is long gone and is not used by all other projects, not to mention it has been inaccessible for a long time and only prevents from following the release pipeline.
> Remove the release-qa-tests

- .circleci/config.yml
The previously used one has been removed from CircleCI.
> Update the machine for CircleCI.

- Cargo.lock
- redis_json/src/lib.rs
Changes the way the module version is specified to always get the crate version from the Cargo.toml. This greatly reduces the chances of accidentally forgetting to update the module version.
> Always use the cargo package version as the module version.

- Cargo.lock
- redis_json/src/lib.rs
Changes the way the module version is specified to always get the crate version from the Cargo.toml. This greatly reduces the chances of accidentally forgetting to update the module version.
> Always use the cargo package version as the module version. (#1254)

- redis_json/src/ivalue_manager.rs
[MOD-7742](https://redislabs.atlassian.net/browse/MOD-7742) Reduce complexity of `JSON.ARRINSERT` from `O(arr.len * args.len)` to `O(arr.len + args.len)`
[MOD-7742]: https://redislabs.atlassian.net/browse/MOD-7742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOD-7742 Reduce time complexity of JSON.ARRINSERT

- Cargo.lock
- Cargo.toml
- redis_json/Cargo.toml
- redis_json/src/commands.rs
- redis_json/src/defrag.rs
- redis_json/src/lib.rs
- tests/pytest/test_defrag.py
The PR adds support for active defrag on RedisJSON. A pre condition for this PR is that the following PR's will be megred:
* [Redis defrad module API extentions](https://github.com/redis/redis/pull/13509)
* [redismodule-rs support for active defrag API](https://github.com/RedisLabsModules/redismodule-rs/pull/387)
* [IJSON support for defrag](https://github.com/RedisJSON/ijson/pull/1)
The PR register defrag function on the json datatype and uses the new capability of ISON to defrag the key.
**Notice**:
* Increamental defrag of the json key is **not** support. In order to support it we need to implement the free_effort callback. This is not trivial and even if it was it would have cause the json object to potentially be freed when the GIL is not hold, which violate the assumption of our …
> RED-134847 support for active defrag for RedisJSON.

- Cargo.lock
- Cargo.toml
- redis_json/Cargo.toml
- redis_json/src/commands.rs
- redis_json/src/defrag.rs
- redis_json/src/lib.rs
- tests/pytest/test_defrag.py
The PR adds support for active defrag on RedisJSON. A pre condition for this PR is that the following PR's will be megred:
* [Redis defrad module API extentions](https://github.com/redis/redis/pull/13509)
* [redismodule-rs support for active defrag API](https://github.com/RedisLabsModules/redismodule-rs/pull/387)
* [IJSON support for defrag](https://github.com/RedisJSON/ijson/pull/1)
The PR register defrag function on the json datatype and uses the new capability of ISON to defrag the key.
**Notice**:
* Increamental defrag of the json key is **not** support. In order to support it we need to implement the free_effort callback. This is not trivial and even if it was it would have cause the json object to potentially be freed when the GIL is not hold, which violate the assumption of our …
> RED-134847 support for active defrag for RedisJSON. (#1262)

- .github/workflows/benchmark-flow.yml
- Cargo.lock
- Cargo.toml
- redis_json/src/lib.rs
RED-137916 When bigredis is used, serialization and deserialization of data might happened outside of the main thread. In this case we need to enable thread safety feature for ijson.
> RED-137916 Enable thread safe on bigredis

- redis_json/src/commands.rs
- redis_json/src/ivalue_manager.rs
- redis_json/src/manager.rs
- redis_json/src/redisjson.rs
(cherry picked from commit f611a961ff38fa18d555de28c3540e06ed45897b)
> fix get_memory to prevent crash on CRDT (#1313)

- Cargo.toml
Bump redismodule-rs version to include a fix where we don't send NULL as `argv` when we are loading a module with no args
> Bump to redismodule-rs 1.0.2 [2.4] [MOD-8549]

- .cargo/config.toml
Hey :wave: 
Following the change of licence, I'm trying to package redis modules for exherbo linux.
To do so effectively, I need the rustflags to be an array instead of a string to better handle merges.
Also, is it in the roadmap of Redis to merge the modules' codebases in the redis repository given the code for vectorsets is already in it ?
Thanks for the good work :)
exherbo mr: https://gitlab.exherbo.org/exherbo/net/-/merge_requests/2335
> Facilitate exherbo packaging
