docs/index.md
After talking with @itamarhaber 
I added client support module I wrote for go lang
I also specified the go-clients the client type
=> Added rejonson module to the client libraries and added client types

docs/index.md
I have worked on making a Ruby client for ReJSON
Please have a look at https://github.com/vachhanihpavan/rejson-rb and provide suggestions.
Thank you :)
=> Added Ruby client for Rejson

src/commands/index.rs, src/redisjson.rs, test/pytest/test.py
Reopen PR from https://github.com/RedisJSON/RedisJSON2/pull/81/
=> Support Object in ARRINDEX

Cargo.lock, Cargo.toml, src/commands/index.rs, src/lib.rs, src/redisjson.rs
Copy from https://github.com/RedisJSON/RedisJSON2/pull/76/
=> fix #151 Don't return deleted docs on qget

Cargo.lock, Cargo.toml, docs/commands.md, src/formatter.rs, src/lib.rs, src/redisjson.rs, test/pytest/test.py
=> Fix #145 - support for get formatting.

docs/index.md
=> adding redis cloud to docs

src/json_path.c, test/pytest/test.py
=> Fix #103 Validate path is not empty

Cargo.lock, Cargo.toml, src/commands/index.rs, src/lib.rs
Update the code with the necessary API changes.
=> Update to new redismodule-rs and redisearch-api-rs releases

README.md, docs/index.md
* Replace chat with Discord
* Update index.md
(cherry picked from commit 47ef6240d9e87ef76c72bb483abf6b9da0bd8b47)
=> Discord (#232)

README.md
=> Update README.md to mention that Rust needs to be installed to build

docs/index.md
(cherry picked from commit e0c6fe4e12d3ffd1726b8c44fd866895243c5b86)
=> add stars to docs

docs/commands.md, mkdocs.yml
* Depth changed to exclude subfields for commands
* Commands broken into sections
* Commands order changed
Look after the change -
=> Redesign command docs

docs/index.md
See https://github.com/RedisJSON/RedisJSON/issues/259
=> Added clarification for module built as dylib to help Mac OS users

docs/index.md
* Fix 404ing command anchors
* Update index.md
Co-authored-by: Guy Korland <gkorland@gmail.com>
(cherry picked from commit c520991afacee5fd83d7898f4f6ef53328aadd1a)
=> Fix 404ing command anchors (#283)

src/lib.rs, src/redisjson.rs
=> Add fake aux load

Dockerfile
Needed to support keyspace notifications
=> Update to Redis 6.2.2

.circleci/config.yml
For the sake of redislabs/rejson Dockerhub build.
=> Platform build for Debian Buster

tests/benchmarks/json_vs_hashes_hset_key_simple.yml, tests/benchmarks/json_vs_hashes_json.set_key_simple.yml
The following PR cherry picks #377 to RedisJSON v1.0.
=> cherry pick: Included hset vs json comparison benchmark use-cases

.circleci/config.yml, Cargo.lock, Cargo.toml
(cherry picked from commit 8adfd29d4d49b6edfcab4465f3f1aa8c6c3d5b6f)
=> [2.0] Fixes in config.yml (#409)

src/redisjson.rs, tests/pytest/test.py, tests/pytest/test_keyspace_notifications.py
Will not break existing clients (expecting a single value)
=> json.get returns a top-level array (as bulk string)

src/redisjson.rs, tests/pytest/test.py, tests/pytest/test_keyspace_notifications.py
* json.get returns a top-level array (as bulk string)
* Fix format and tests
(cherry picked from commit cc6d22583f86f30f0bfab5418c226dfea0af6eab)
=> Merge PR #411 from master to 2.0

tests/pytest/test.py
Add coverage for JSON paths with implicit dot notation
=> Add testGetWithBracketNotation

src/rejson.c, test/pytest/test.py
=> Change first key index to 2

src/c_api.rs, src/lib.rs
The API used on Search side is long long 
https://github.com/RediSearch/RediSearch/blob/00d143505fffe86456c73950bdea411f284ac104/src/rejson_api.h#L43
=> fix #451 getInt should return long long

docs/index.md
=> Replaces "Redis Labs" with "Redis".

src/manager.rs, tests/pytest/test.py
=> Avoid crash in ARRTRIM

src/manager.rs, tests/pytest/test_multi.py
Fix #508
Avoid crash
(merge from https://github.com/freestrings/jsonpath/pull/70)
=> Multipath: avoid crash on del

Cargo.lock, Cargo.toml, src/commands.rs, src/manager.rs, tests/pytest/test_multi.py
=> Multipath - del handles multi (wildcard, etc.)

.circleci/config.yml, Cargo.lock, Cargo.toml, Makefile, build.rs, src/commands.rs, src/lib.rs, src/manager.rs, src/redisjson.rs, tests/pytest/test_multi.py, tests/qa/qatests
=> Merge to 2.0 from master (4) and update version to 2.0.3

src/commands.rs, tests/pytest/test_multi.py
Need to delete a longer path before a shorter path, if longer path has higher array index compared to the shorter path
Fixes #529
=> Multipath - DEL - order by array index even if path lengths are different

docs/commands.md, docs/indexing_JSON.md, docs/path.md
* Document new path, JSON.GET and JSON.MGET
* Add examples and update results for all commands
* Update complexity information
* Update docs/commands.md
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* Update docs/commands.md
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* Add example to NUMINCRBY. Fix example in NUMMULTBY
* Update docs/commands.md
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* Update docs/commands.md
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* Post review rephrasing
* Update docs/commands.md
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* Add indexing JSON documents
* Post review
* Update docs/indexing_JSON.md
Co-authored-by: Omer Shadmi …
=> Doc 2.0 (#538)

.circleci/config.yml, Dockerfile, Makefile, build/docker/dockerfile.tmpl, build/platforms/Dockerfile, sbin/pack.sh
(cherry picked from commit c3ed883805af6f6413061fb65027f6d04497630a)
=> [2.0] ARM support (#550)

.circleci/config.yml, Makefile
(cherry picked from commit b1c8cb402a17ff142b7fe8e590a10e98726fef1b)
=> Build ARM for bionic; test with Redis 6.0 (#556)

docs/indexing_JSON.md, docs/path.md
@emmanuelkeller Here are some more copyedit suggestions for the docs.
=> Copyedit suggestions for path.md and indexing_JSON.md

Cargo.lock, Cargo.toml, src/lib.rs
Corresponding change to redismodule-rs PR [#211](https://github.com/RedisLabsModules/redismodule-rs/pull/211)
=> Add info func to redis_json_module_create macro

docs/commands.md
=> Cherry-pick doc fix to 2.0

tests/pytest/test.py
=> Add test for JSON.SET adding a new direct/immediate child

src/commands.rs, tests/pytest/test_multi.py
=> MOD-2511: do not fail MGET on wrong key type

Cargo.lock, Cargo.toml, tests/pytest/test.py
Related https://github.com/RedisLabsModules/redismodule-rs/pull/218
And https://github.com/RedisLabsModules/redismodule-rs/pull/200
=> MOD-2484: add test with illegal chars in path

docs/index.md
Hi, I made a Golang Redis client library that supports RedisJSON commands.
Could I add my library to the client list? Thanks!
=> Add rueidis to client list

Cargo.lock, Cargo.toml, src/c_api.rs, src/commands.rs, src/ivalue_manager.rs
And clean some clippy warnings
=> Bump dep redismodule-rs to v1.0.0

Cargo.lock, Cargo.toml, src/lib.rs
=> Revert bad merge (2)

Cargo.lock, Cargo.toml, tests/pytest/test.py
(cherry picked from commit 8dbef98d5d0a62c1b47456e62944568e1af42fbd)
=> Omer cherry-pick #671 to 2.0

docs/commands.md
(cherry picked from commit 3352ac962e889dff987ebafacfd7a103bbecc363)
=> CP to 2.0 Fix JSON.CLEAR doc

Cargo.lock, tests/pytest/test_multi.py
Take the fix in jsonpath lib for #667 and add test
=> Use jsonpath lib with fix for issue #667

commands.json, docs/commands/json.clear.md, src/commands.rs, src/ivalue_manager.rs, src/manager.rs, tests/pytest/test.py, tests/pytest/test_multi.py
=> MOD-3136: Skip String and Bool scalars in `JSON.CLEAR`

src/lib.rs, src/redisjson.rs, tests/pytest/test.py
=> Add support for Copy

docs/docs/path.md
Updated path.md:
• Added JSONPath syntax table
• Added JSONPath examples
• Updated description
• Added links
• Mild copy edits
=> Added JSONPath syntax examples to path.md

docs/commands/json.strappend.md
=> Fix typo in doc of JSON.STRAPPEND

commands.json
=> Path in Toggle is not optional

src/jsonpath/grammer.pest, tests/rust_tests/filter.rs
(cherry picked from commit ce225df065813236a7810eadb112dd69380eca1e)
=> [2.4] Allow repetition of filter relation instead of optional (#850)

docs/docs/_index.md
Fixes https://github.com/redis/redis-doc/issues/2179
=> Fixes link

.circleci/config.yml, .github/workflows/freebsd.yml, Makefile
(cherry picked from commit 33de90f591b3bf25a8617f20f9bbcdd5aba0777e)
=> [2.2] Updated readies & more nightly builds (#860)

src/c_api.rs, src/include/rejson_api.h, src/redisjson.rs, tests/pytest/test.py
=> [2.4] Cherry-picks from master

docs/docs/ram.md
=> Fix JSON.DEBUG malformed link

docs/docs/path.md
=> Document clearly when filter regex match was introduced

docs/commands/json.get.md, docs/docs/path.md
Fixes #882, explains returns of JSON array and JSON object
=> [DOC UPDATE] Update return info in JSON.GET topics 

.github/wordlist.txt, Cargo.lock, Cargo.toml, src/jsonpath/json_path.rs, src/jsonpath/mod.rs, tests/pytest/test.py, tests/rust_tests/common.rs
=> MOD-4602: handle jsonpath filter with 3 or more operands

README.md, docs/docs/Clients.md
[rustis](https://github.com/dahomey-technologies/rustis)
=> Added `rustis` client library

src/ivalue_manager.rs, tests/pytest/test_multi.py
ref https://github.com/Diggsey/ijson/issues/23
=> MOD-4787: Calculate the IValue actual memory usage

src/jsonpath/grammer.pest, src/jsonpath/mod.rs
(cherry picked from commit a2fdfb432bb4b9c9aa8b800dcbe74163133d6346)
=> fix #947 step value can only positive none zero (#952)

src/lib.rs
=> last key index should be -1

redis_json/src/commands.rs, tests/pytest/test_keyspace_notifications.py
=> [2.6] - Fix JSON.TOGGLE key space notification

src/commands.rs, tests/pytest/test_keyspace_notifications.py
=> [2.4] - Fix JSON.TOGGLE key space notification

redis_json/src/formatter.rs, redis_json/src/ivalue_manager.rs, redis_json/src/key_value.rs, redis_json/src/redisjson.rs, tests/pytest/test_resp3.py
=> Set FORMAT EXPAND as default

docs/docs/_index.md
Fixed a broken link after the docs reorg.
=> docs: Fixes broken link

redis_json/src/c_api.rs, redis_json/src/include/rejson_api.h, redis_json/src/lib.rs
Test will be in RediSearch/RediSearch#3707 (until MOD 4159 is done)
=> MOD-5390: Add C API to iterate a JSON Object

.circleci/config.yml
=> Temp trigger of mac build and upload

.circleci/config.yml
=> Revert temp changes Mac

Cargo.lock, redis_json/Cargo.toml, redis_json/src/lib.rs
Needed for changes on RedisJsonHdt
=> MOD-5617: Bump version to 2.6.6

.circleci/config.yml
=> MOD-5753: Fix macos-x64 build

.circleci/config.yml
=> [2.6] MOD-5753: Fix macos-x64 build #1082

.circleci/config.yml, build/docker/Makefile, sbin/get-redisearch, sbin/pack.sh, sbin/system-setup.py, sbin/upload-artifacts
Cherry pick MOD-5762: RockyLinux 9 support to 2.6.
=> [2.6] CP MOD-5762: RockyLinux 9 support

redis_json/src/c_api.rs, redis_json/src/lib.rs
=> Fix compilation also when used by RedisJsonHdt

.circleci/config.yml
bool `run_nightly_twice_a_week_flow_label` (default false)
=> Add CircleCi param to trigger nightly-twice-a-week manually

Cargo.lock, redis_json/Cargo.toml, redis_json/src/lib.rs
bump branch 2.6 to version 2.6.8
=> [2.6] bump to version 2.6.8

.circleci/config.yml, sbin/pack.sh, sbin/upload-artifacts
=> Upload artifact fix [2.4] [MOD-6102]

.circleci/config.yml
Fix upload artifacts to staging job (this will probably not must since we already upload from each platform job - temp fix until refactor)
=> Fix upload to staging failure

Makefile
CP #1158 to 2.4.
(cherry picked from commit 8222b61d50d1d9dd4df6a937c6f17a8d576aab6d)
=> [2.4] MOD-6283: Use new RLTest but with no-progress

.github/workflows/freebsd.yml, Cargo.lock, redis_json/Cargo.toml
=> Backport 1163 to 2.6

.github/workflows/freebsd.yml, Cargo.lock, Cargo.toml, src/ivalue_manager.rs, src/serde_value_manager.rs
=> Backport !1163 to 2.4

.circleci/config.yml, Cargo.lock, Cargo.toml, Makefile, json_path/Cargo.toml, redis_json/Cargo.toml, redis_json/src/c_api.rs, redis_json/src/formatter.rs, redis_json/src/ivalue_manager.rs, redis_json/src/lib.rs, sbin/install_clang.sh, sbin/update_clang_alternatives.sh, tests/pytest/test_short_read.py, tests/pytest/tests.sh
=> [MOD-7289,   MOD-7306, MOD-7305] Update base RDBs URL

redis_json/src/commands.rs, redis_json/src/ivalue_manager.rs, redis_json/src/manager.rs, tests/pytest/test.py
1. Write to AOF outside the iterator
2. Added notify_keyspace_event API to manager
=> MOD-7293 fix AOF commands duplicated in JSON.MSET

.circleci/config.yml, Cargo.lock, Cargo.toml, Makefile, json_path/Cargo.toml, redis_json/Cargo.toml, redis_json/src/c_api.rs, redis_json/src/commands.rs, redis_json/src/formatter.rs, redis_json/src/ivalue_manager.rs, redis_json/src/lib.rs, redis_json/src/manager.rs, sbin/install_clang.sh, sbin/update_clang_alternatives.sh, tests/pytest/test.py, tests/pytest/test_short_read.py, tests/pytest/tests.sh
changes: 
MOD-7293 fix AOF commands duplicated in JSON.MSET  https://github.com/RedisJSON/RedisJSON/pull/1212 
---------
CI fixes: 
- https://github.com/RedisJSON/RedisJSON/pull/1211
- https://github.com/RedisJSON/RedisJSON/pull/1214
=> 2.6 with aof merge fix

.circleci/config.yml
Fix the CI by updating the macos version.
=> Fix the CI issues. (#1231)

Cargo.lock, json_path/Cargo.toml, json_path/src/json_path.rs, redis_json/src/commands.rs, redis_json/src/ivalue_manager.rs, redis_json/src/key_value.rs, redis_json/src/redisjson.rs, tests/pytest/test.py
=> [2.6] Cherry-pick #1225 - Fix SET commands with overlapping paths

Cargo.lock, json_path/Cargo.toml, json_path/src/json_path.rs, redis_json/src/commands.rs, redis_json/src/ivalue_manager.rs, redis_json/src/key_value.rs, redis_json/src/redisjson.rs, tests/pytest/test.py
=> [2.8] Cherry-pick #1225 - Fix SET commands with overlapping paths

.github/actions/build-json-module-and-redis-with-cargo/action.yml, .github/workflows/ubuntu-arm.yml
Addendum to #1270, updating uploaded module library name from `librjson.so`/`.dylib` to `rejson.so`
=> Fix module lib name

tests/pytest/requirements.txt
=> MOD-7946 backport 1279 to 2.8

tests/pytest/requirements.txt
=> MOD-7946 backport 1279 to 2.4

.github/workflows/macos-build-and-deploy.yml
[MOD-7858](https://redislabs.atlassian.net/browse/MOD-7858)
[MOD-7859](https://redislabs.atlassian.net/browse/MOD-7859)
[MOD-7858]: https://redislabs.atlassian.net/browse/MOD-7858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOD-7859]: https://redislabs.atlassian.net/browse/MOD-7859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-7858 MOD-7859 Add workflow dispatch to monterrey

.github/workflows/macos-build-and-deploy.yml
* initial
* fix
(cherry picked from commit 554e4d859e5eaccc5d3d9add9e8fa7c8ad8acc12)
=> MOD-7858 Add workflow dispatch to monterrey (#1283)

.github/workflows/macos-build-and-deploy.yml
* initial
* fix
(cherry picked from commit 554e4d859e5eaccc5d3d9add9e8fa7c8ad8acc12)
=> MOD-7859 Add workflow dispatch to monterrey (#1283)

Cargo.lock, Cargo.toml, redis_json/src/lib.rs
(cherry picked from commit d65d9a482ef7c2d00c582b025cca827be6d3d516)
=> RED-137916 Enable thread safe on bigredis (#1293)

.github/workflows/macos-build-and-deploy.yml, redis_json/src/commands.rs, redis_json/src/ivalue_manager.rs, redis_json/src/manager.rs, redis_json/src/redisjson.rs
(cherry picked from commit https://github.com/RedisJSON/RedisJSON/commit/f611a961ff38fa18d555de28c3540e06ed45897b)
=> fix get_memory to prevent crash on CRDT (#1313)

json_path/src/json_node.rs, redis_json/src/commands.rs, redis_json/src/redisjson.rs, tests/pytest/test.py
[MOD-9117](https://redislabs.atlassian.net/browse/MOD-9117)
[MOD-9117]: https://redislabs.atlassian.net/browse/MOD-9117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-9117 DEL key upon JSON.DEL emptying root

json_path/src/json_node.rs, redis_json/src/commands.rs, redis_json/src/redisjson.rs, tests/pytest/test.py
* DEL key upon JSON.DEL emptying root
* fix tests
(cherry picked from commit f3d6cd9a2e6809aedf92c3a25948729500f69b6c)
=> MOD-9117 DEL key upon JSON.DEL emptying root (#1336)

.github/workflows/event-ci.yml, .github/workflows/event-nightly.yml, .github/workflows/event-tag.yml, .github/workflows/flow-linux-x86.yml, .github/workflows/freebsd.yml, .install/microsoft_azure_linux_3.0.sh
Also disabled the freebsd github workflow (the code doesn't even compile there)
(cherry picked from commit 47b4430d13f7258e607ecf4e3eb295e85317214f)
=> MOD-9172 Add Azure Linux 3 support (#1335)

Cargo.lock, Cargo.toml, redis_json/src/ivalue_manager.rs, tests/pytest/test_multi.py, tests/pytest/test_resp3.py
[MOD-9575](https://redislabs.atlassian.net/browse/MOD-9575)
[MOD-9575]: https://redislabs.atlassian.net/browse/MOD-9575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-9575 Delegate memory stats to IJson

Cargo.lock, Cargo.toml, redis_json/src/ivalue_manager.rs, tests/pytest/test_defrag.py, tests/pytest/test_multi.py
[MOD-9511](https://redislabs.atlassian.net/browse/MOD-9511)
[MOD-9511]: https://redislabs.atlassian.net/browse/MOD-9511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-9511 update memory stats to inlined numbers

.github/workflows/event-ci.yml, .github/workflows/event-nightly.yml, .github/workflows/event-tag.yml, .github/workflows/event-weekly.yml, .github/workflows/flow-azurelinux3-arm.yml
* Support azure linux 3 arm
* fix
(cherry picked from commit 489cfc6abe6a223d8ee0112becd6cbf292a8813c)
=> Support azure linux 3 arm (#1357)

json_path/src/json_path.rs, json_path/src/lib.rs, redis_json/src/commands.rs, tests/pytest/test.py
…#1377)
* MOD-11032 fix incorrect comparission between numaric indicies in pathes
* remove print from test
(cherry picked from commit 03942be497bd8366eb2d54888d20a826c5d9c61d)
=> MOD-11183 Avivd cherry pick 2.8 2 commits from 03942be
